name: CI Build

on:
  push:
jobs:
  Build:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        mode: [ Debug, ReleaseSafe, ReleaseSmall ]
        target: [ native, x86_64-linux-gnu, x86_64-linux-musl, aarch64-linux-gnu, x86_64-macos, aarch64-macos, x86_64-windows, aarch64-windows ]
    name: ${{ matrix.os }}, ${{ matrix.target }}-${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout repo

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0-dev.1911+3bf89f55c
    
      - name: Build 
        run: zig build -Doptimize=${{ matrix.mode }} -Dtarget=${{ matrix.target }}

      - name: Upload
        if: matrix.os == 'ubuntu-latest' && matrix.target != 'native' && matrix.mode == 'ReleaseSmall'
        uses: actions/upload-artifact@v4
        with:
          path: zig-out/bin
          name: ${{ matrix.target }} - ${{ matrix.mode }}